
/* Drop Tables */

DROP TABLE BOOK_RETURN CASCADE CONSTRAINTS;
DROP TABLE BOOK_LEND CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BOOK
(
	BOOK_NAME varchar2(50) NOT NULL,
	BOOK_NO number(10,0) NOT NULL,
	BOOK_TYPE varchar2(10),
	BOOK_POSITION varchar2(10),
	BOOK_WRITER varchar2(10),
	BOOK_PUBLISHER varchar2(30),
	BOOK_STATE varchar2(10),
	BOOK_COUNT number(10,0),
	PRIMARY KEY (BOOK_NAME)
);


CREATE TABLE BOOK_LEND
(
	MEMBER_ID varchar2(30) NOT NULL,
	BOOK_NAME varchar2(50) NOT NULL,
	BOOK_LEND_NO number(10,0) NOT NULL,
	BOOK_LEND_DATE date,
	BOOK_LEND_DEADLINE date,
	BOOK_LEND_COUNT number(10,0),
	PRIMARY KEY (BOOK_LEND_NO)
);


CREATE TABLE BOOK_RETURN
(
	BOOK_LEND_NO number(10,0) NOT NULL,
	BOOK_NAME varchar2(50) NOT NULL,
	BOOK_RETURN_DATE date,
	BOOK_RETURN_AEEAARS varchar2(10)
);


CREATE TABLE MANAGER
(
	MANAGER_GRADE varchar2(30) NOT NULL,
	MANAGER_ID varchar2(10),
	MANAGER_NAME varchar2(10),
	PRIMARY KEY (MANAGER_GRADE)
);


CREATE TABLE MEMBERS
(
	MEMBER_ID varchar2(30) NOT NULL,
	MEMBER_PW varchar2(30),
	MEMBER_NAME varchar2(10),
	MEMBER_AGE number(10,0),
	MEMBER_EMAIL varchar2(30),
	MEMBER_PHONE varchar2(30),
	MEMBER_ADDRESS varchar2(50),
	MANAGER_GRADE varchar2(30) NOT NULL,
	PRIMARY KEY (MEMBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE BOOK_LEND
	ADD FOREIGN KEY (BOOK_NAME)
	REFERENCES BOOK (BOOK_NAME)
;


ALTER TABLE BOOK_RETURN
	ADD FOREIGN KEY (BOOK_NAME)
	REFERENCES BOOK (BOOK_NAME)
;


ALTER TABLE BOOK_RETURN
	ADD FOREIGN KEY (BOOK_LEND_NO)
	REFERENCES BOOK_LEND (BOOK_LEND_NO)
;


ALTER TABLE MEMBERS
	ADD FOREIGN KEY (MANAGER_GRADE)
	REFERENCES MANAGER (MANAGER_GRADE)
;


ALTER TABLE BOOK_LEND
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBERS (MEMBER_ID)
;



